driver:
  ros__parameters:
    port: "/dev/ttyUSB0"
    baudrate: 115200
    publish_rate_hz: 10.0
    command_timeout_sec: 1.0
    invert_motor_1: false # left front
    invert_motor_2: true # right front
    invert_motor_3: true # left_rear
    invert_motor_4: false # right rear
    max_linear: 30.0 # speed
    max_angular: 30.0 # turning
